name: github_metadata
on:
  pull_request_target:
    types: [assigned, labeled, opened, synchronize, reopened]

jobs:
  check:
    name: Protect github metadata
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'github-metadata-change') }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      GIT_DIR: git-dir.git
    steps:
      - name: Fetch PR
        run: |
          set -x
          git init -b main
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          git fetch origin '${{ github.event.pull_request.head.sha }}'

      - name: Check for changes to .github/
        run: git diff --exit-code '${{ github.sha }}' '${{ github.event.pull_request.head.sha }}' -- .github
